name: Deploy ke Vercel (via dummy)

on:
  push:
    branches:
      - main

jobs:
  notice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Informasi Deploy
        run: echo "Deploy otomatis dilakukan oleh Vercel. Workflow ini hanya contoh."
